import type { Metadata } from 'next'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import styles from './legal.module.css'

export const metadata: Metadata = {
  title: 'Privacy Policy | Hedge Payments',
  description:
    'How Hedge, Inc. collects, uses, stores and protects personal and financial information, including bank account data accessed through Stripe Financial Connections.',
}

const EFFECTIVE = 'August 26, 2026'

export default function PrivacyPolicy() {
  return (
    <main>
      <Navbar />
      <article className={styles.wrap}>
        <p className={styles.eyebrow}>Legal</p>
        <h1 className={styles.title}>Privacy Policy</h1>
        <p className={styles.meta}>
          Hedge, Inc. &middot; Effective {EFFECTIVE} &middot;{' '}
          <a href="/terms">Terms of Service</a>
        </p>

        <ul className={styles.toc}>
          <li><a href="#scope">1. Who this covers</a></li>
          <li><a href="#collect">2. Information we collect</a></li>
          <li><a href="#bank">3. Bank account data and Stripe Financial Connections</a></li>
          <li><a href="#use">4. How we use information</a></li>
          <li><a href="#share">5. How we share information</a></li>
          <li><a href="#retain">6. Storage, security and retention</a></li>
          <li><a href="#choices">7. Your choices and rights</a></li>
          <li><a href="#children">8. Children</a></li>
          <li><a href="#changes">9. Changes</a></li>
          <li><a href="#contact">10. Contact</a></li>
        </ul>

        <h2 id="scope">1. Who this covers</h2>
        <p>
          Hedge, Inc. (&ldquo;Hedge&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) provides payments technology to
          businesses, including a round-up tool that lets a consumer round transactions up to the nearest dollar
          and move the difference from their bank account into a digital wallet. This policy describes how we
          handle information when you use our websites, our round-up and wallet services, and any Hedge feature
          embedded in a business partner&rsquo;s app or site (together, the &ldquo;Services&rdquo;).
        </p>
        <p>
          Our business partners (the merchants or apps in which our Services are embedded) have their own privacy
          policies that govern the information they collect. This policy covers only what Hedge collects and
          processes.
        </p>

        <h2 id="collect">2. Information we collect</h2>
        <h3>Information you or a partner provide</h3>
        <ul>
          <li>Identity and contact details: name, email address, phone number.</li>
          <li>A partner-assigned user identifier so we can associate round-ups with your account at that partner.</li>
          <li>Bank account details you enter manually (routing and account number) when linking an account without
            an instant-verification flow.</li>
          <li>Your authorization (mandate) to debit your bank account, including the time, IP address and device
            information at the moment you accepted it.</li>
        </ul>
        <h3>Information generated by using the Services</h3>
        <ul>
          <li>Transaction amounts that trigger round-ups, the round-up amounts, and the status of each debit
            (initiated, processing, settled, returned, failed).</li>
          <li>Wallet balances and wallet activity (credits, transfers, reversals).</li>
          <li>Technical data: IP address, browser/device type, timestamps and logs used for security, fraud
            prevention and troubleshooting.</li>
        </ul>

        <h2 id="bank">3. Bank account data and Stripe Financial Connections</h2>
        <div className={styles.callout}>
          <p>
            When you link a bank account through an instant-verification flow, that flow is provided by Stripe
            Financial Connections. You authenticate directly with your bank; Hedge never sees your online banking
            username or password.
          </p>
        </div>
        <p>Through Financial Connections we receive only the following, with your permission:</p>
        <ul>
          <li>
            <strong>Tokenized account and routing numbers</strong> &mdash; used solely to initiate the ACH debits you
            have authorized.
          </li>
          <li>
            <strong>Account balance</strong> &mdash; checked before a debit to reduce the chance of an overdraft or
            a returned payment.
          </li>
        </ul>
        <p>
          We do not request or receive your transaction history or account ownership details through Financial
          Connections. We do not sell Financial Connections data, do not use it for marketing, and do not use it as
          part of any consumer report. Bank data obtained through Financial Connections is stored in the United
          States and is not shared with third parties other than Stripe (which processes it under its own{' '}
          <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer">privacy policy</a>) and the
          banks involved in processing a payment.
        </p>
        <p>
          You can disconnect a linked bank account at any time through the partner app, by contacting us, or
          through your bank&rsquo;s connected-apps settings where offered. Disconnecting revokes our ability to
          initiate new debits but does not reverse payments already in progress.
        </p>

        <h2 id="use">4. How we use information</h2>
        <ul>
          <li>To provide the Services: calculate round-ups, initiate and track ACH debits, maintain wallet balances
            and process transfers.</li>
          <li>To verify bank accounts and comply with Nacha rules and other payment-network requirements, including
            keeping a record of your debit authorization.</li>
          <li>To detect and prevent fraud, unauthorized use, returned payments and abuse.</li>
          <li>To provide support, send transactional notices (for example, confirmation of a debit authorization or a
            returned payment) and respond to your requests.</li>
          <li>To comply with law, respond to lawful requests, and enforce our terms.</li>
          <li>To operate, secure and improve the Services, using aggregated or de-identified data where possible.</li>
        </ul>
        <p>We do not use your information to serve third-party advertising.</p>

        <h2 id="share">5. How we share information</h2>
        <ul>
          <li>
            <strong>Payment processors and banks.</strong> Stripe and the financial institutions involved in an ACH
            transaction receive the information needed to process it.
          </li>
          <li>
            <strong>Business partners.</strong> The partner whose app you used to enroll receives the status and
            amounts of your round-ups and wallet activity related to their program, and your partner user
            identifier. They do not receive your full bank account number from us.
          </li>
          <li>
            <strong>Service providers.</strong> Hosting, database, logging and customer-support vendors that process
            data on our behalf under contractual confidentiality obligations.
          </li>
          <li>
            <strong>Legal and safety.</strong> When required by law, subpoena or regulator, or to protect the rights,
            property or safety of Hedge, our users or others.
          </li>
          <li>
            <strong>Business transfers.</strong> In connection with a merger, acquisition or sale of assets, subject
            to this policy.
          </li>
        </ul>
        <p>We do not sell personal information.</p>

        <h2 id="retain">6. Storage, security and retention</h2>
        <p>
          Data is stored on servers located in the United States. Bank account credentials you enter manually are
          transmitted directly to our payment processor and are not retained by Hedge in plain text; stored
          partner-provider credentials are encrypted at rest (AES-256-GCM). Access to production systems is
          restricted and logged.
        </p>
        <p>
          We retain transaction records, debit authorizations and related identity information for as long as
          needed to provide the Services and for the periods required by payment-network rules, tax and
          anti-fraud laws (generally up to seven years after the last transaction). Financial Connections data is
          retained only as long as the linked account remains connected and as required to complete or dispute
          payments already initiated. No method of transmission or storage is completely secure; if we become aware
          of a breach affecting your information we will notify you as required by law.
        </p>

        <h2 id="choices">7. Your choices and rights</h2>
        <ul>
          <li>You can stop round-ups or disconnect a bank account at any time through the partner app or by
            contacting us.</li>
          <li>You can request access to, correction of, or deletion of your personal information. We may retain
            information we are legally required to keep (for example, records of completed payments).</li>
          <li>Residents of California and other states with comprehensive privacy laws may have additional rights,
            including the right to know what information we hold and the right to non-discrimination for exercising
            those rights. We do not sell or share personal information for cross-context behavioral advertising.</li>
        </ul>
        <p>
          To exercise any of these rights, email{' '}
          <a href="mailto:support@hedgepayments.com">support@hedgepayments.com</a>. We will verify your identity
          before acting on a request.
        </p>

        <h2 id="children">8. Children</h2>
        <p>
          The Services are not directed to anyone under 18, and we do not knowingly collect information from
          children. If you believe a minor has provided us information, contact us and we will delete it.
        </p>

        <h2 id="changes">9. Changes</h2>
        <p>
          We may update this policy from time to time. We will post the revised version here with a new effective
          date and, for material changes, notify you through the Services or by email.
        </p>

        <h2 id="contact">10. Contact</h2>
        <p>
          Hedge, Inc.<br />
          Email: <a href="mailto:support@hedgepayments.com">support@hedgepayments.com</a><br />
          Web: <a href="https://hedgepayments.com">hedgepayments.com</a>
        </p>
      </article>
      <Footer />
    </main>
  )
}
